jewel:
   name: tokenup-worker-www
   port: 8080
   rest:
      default:
         enabled: false
   register:
        etcd_plugin:
               urls: http://localhost:2379
               enabled: true






