jewel:
   name: tokenup-worker-www
   server:
      port: 8088
      gin_mode: debug
      manager:
         enabled: true
         user: test
         password: test
   mgo:
      default:
         address: 18.136.124.100:27017
         database: tokenup-eos
         pool_limit: 10
         timeout: 5000
   rest:
      default:
         enabled: false
   register:
        etcd_plugin:
               urls: http://localhost:2379
               enabled: true
               refresh_timeout: 90000






